
project_id = "jvmmgamfdbgdjjptfkgy"

[functions.create-checkout]
verify_jwt = false

[functions.handle-stripe-webhook]
verify_jwt = false

[functions.generate-outfit-suggestion]
verify_jwt = true

[functions.generate-outfit-suggestion-hf]
verify_jwt = true

[functions.get-weather]
verify_jwt = false

[functions.get-suitcase-suggestions]
verify_jwt = true

[functions.generate-mistral-suggestion]
verify_jwt = true

[functions.get-suitcase-suggestions-mistral]
verify_jwt = true
