CREATE TABLE IF NOT EXISTS site_stats (
  id SERIAL PRIMARY KEY,
  category TEXT NOT NULL,
  metric TEXT NOT NULL,
  value NUMERIC NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
